version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies
      - npm install
      - npm install -g serverless

  pre_build:
    commands:
      - echo Fetching Git metadata
      - export GIT_COMMIT_HASH=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - export BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Node.js code
      # - npm run build # if you have a build script

  post_build:
    commands:
      - echo Build completed on `date`
      # - sls deploy --stage $STAGE_NAME
      - sls deploy
      - echo Deployed with Git hash $GIT_COMMIT_HASH, committer $GIT_COMMITTER_NAME at $BUILD_TIMESTAMP

artifacts:
  files:
    - '**/*'

# environment:
#   variables:
#     STAGE_NAME: 'dev'
